ARG PROJECT_ID_ARG
FROM gcr.io/$PROJECT_ID_ARG/helloworld-image

ARG URL_ARG
RUN echo $URL_ARG

WORKDIR /usr/src/app

COPY package*.json ./

COPY tests tests
ENV NODE_ENV test

RUN npm install
COPY . .

RUN npm run test:mocha
