ARG PROJECT_ID_ARG
FROM gcr.io/$PROJECT_ID_ARG/helloworld-image
WORKDIR /usr/src/app

COPY package*.json ./

COPY tests tests
ENV NODE_ENV dev

RUN npm update && \
    npm install -g mocha

CMD ["mocha", "tests/test.js", "--reporter", "spec"]


ENV NODE_ENV dev
